### ISSUE TITLE
Is it possible to auto rename the source file?

### ISSUE THREAD

**Issue by Konfido** [sethyuan/logseq-plugin-luckysheet#1]
(First, it's an incredible plugin, thanks for your amazing work!)

- As the question says is it possible to automatically rename the source file? 
	- I know I can change the name in the UI, but the source file keeps the same and I didn't find where it store the name information. 
	- And I found that I can manually change it without losing my data, but once I make further modifications on the sheet, it will create a new file with the original name.
- I want to make sure all the stored files are at use, otherwise they can be deleted safely.

**Comment by sethyuan** [comment]
Glad you like the plugin, I really put some efforts on it.

Regarding the file name, the reason I didn't use "UI name" as file name is a technical one, "UI name" can have arbitrary characters but file name can't. It is highly probable that users use a name that has characters that are not accepted as a file name character. So what I did was to use a hash of the "UI name" instead, to avoid possible "bad" names which affect file saving. This however, makes identifying files difficult for a human. 😅

I need time to think about this. Maybe I can write "UI name" into the file too, in this way, you can open the file with a text editor to identify it.

**Comment by sethyuan** [comment]
> I need time to think about this. Maybe I can write "UI name" into the file too, in this way, you can open the file with a text editor to identify it.

I implemented it, you can open the sheets with the new version of the plugin and the ui name will be written into the file upon saving.

**Comment by Konfido** [comment]
Cool, I've tried it out. It works like a charm.

BTW, is it feasible to just filter out the unsafe characters and automatically leave the rest as the name (for both UI and the file)? Maybe you can append numbers or something to it when the duplication occurs.
I hope I am not asking too much.

**Comment by sethyuan** [comment]
Filtering unsafe characters is not easy task. Whether a character is valid or not depends on the OS you're working on. A character that is valid for macOS might be invalid for Windows, it would be buggy when you port files across operating systems.

I believe even Logseq itself had many bugs related to incorrect file name handlings in the past, there is too many corner cases (think about all the languages that exist in the world).

**Comment by Konfido** [comment]
> I believe even Logseq itself had many bugs related to incorrect file name handlings in the past, there is too many corner cases (think about all the languages that exist in the world).

Bingo! How about we just take the filename already processed by logseq (which is the page's name) as file name of sheets. And we can append numbers to it when adding multiple sheets in one single page.
At the same time, it does not affect the user's ability to modify the UI name.

**Comment by sethyuan** [comment]
It’s not a good idea to bind a spreadsheet‘s file name to a page name. A spreadsheet is not “owned” by a page, in fact, multiple pages can contain the same spreadsheet, it depends on use case.

Currently, a spreadsheet is uniquely identified by its name, if you use the same name in different pages, you get the same spreadsheet.
