### ISSUE TITLE
Feature Request: Persist to/Read from CSV/TSV

### ISSUE THREAD

**Issue by yingzhu146** [sethyuan/logseq-plugin-luckysheet#11]
Hi @sethyuan, thanks a lot for this plugin!

One way to approach #10 and solve another great use case is to persist the data locally in the assets folder as CSV.

This is very consistent with how logseq handles non-text datatypes
- drawings are persisted in the `draws` subfolder
- images are persisted in the `assets` subfolder
- pdfs are persisted in the `assets` subfolder

Additionally this also enables a lot of other benefits, which I'd be most excited about

- Data is not locked into the serialization format used by luckysheet
- Much easier to handle larger tables in a dedicated table file format than markdown
- Edit data in a dedicated spreadsheet software, view in logseq
- Use tables as databases and reuse them across applications - e.g. do data engineering in a jupyter notebook, then read/view/comment in logseq
- use command-line utilities for quick data engineering - xsv, visidata, cut, ....

One option to implement:

`Save` button persists to disk in asset folder, vs storing in markdown
This could be configurable in the plugin settings

**Comment by sethyuan** [comment]
Great suggestion! In fact, I always wanted to store the content in the assets folder, but it wasn't supported by the Logseq plugin SDK. Storing in markdown is kind of a workaround solution. The good news is, with the release of Logseq 0.8.9, there is a new plugin SDK API that allows to write in the assets folder. I still need to spend some time to test it, once it's assessed, I'll change the save to write to the assets folder and remove markdown storing.

Regarding CSV, it is not a feature rich file format, so many features like formatting, formulas, etc, are not possible with it. Given this restriction, I'm not sure storing in CSV by default is a good idea.

What I can do I think, is to provide an "import/export" functionality. BTW, I think you can already paste a CSV into Luckysheet and use the "Copy selection as TSV" button to "export" the content in TSV.

**Comment by rebron1900** [comment]
0.8.9中不能保存数据到子块的json中了，如图，表格中有数据，但是在往常储存数据的json中没有发生数据变化。：
![image](https://user-images.githubusercontent.com/7929884/196835627-a5374ab5-510a-41e2-a0d1-67cbedf8d188.png)

**Comment by yingzhu146** [comment]
Amazing thank you - what is it saved as? code looks like `json` but grepping for `json` (or csv...) comes up empty handed. tried reinstalling & restarting but no dice

**Comment by sethyuan** [comment]
It's JSON, but it's not two dimensional. It contains all the data and metadata Luckysheet uses.

**Comment by rebron1900** [comment]
@sethyuan thks，i will try to update 0.9.0，The changes to solved many problems.

**Comment by sethyuan** [comment]
BTW, you need to use Logseq v0.8.9+ in order to use the 0.9.0.

**Comment by yingzhu146** [comment]
doesn't seem to work for me - version 0.9.0, logseq 0.8.9
<img width="647" alt="20221021-213231" src="https://user-images.githubusercontent.com/59233975/197310780-fd32fa96-8bc3-4922-8375-ce1221984ee1.png">

<img width="647" alt="20221021-213231" src="https://user-images.githubusercontent.com/59233975/197310789-deafeebc-04fe-4aa3-81e4-7a9c702fe6c0.png">


```
$ pwd
 /Users/yingzhu/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/assets
$ find ./ -name '*.pdf' | wc -l
    1506
$ find ./ -name '*.json' | wc -l
       0
```

**Comment by sethyuan** [comment]
File is stored in your graph's assets folder and they have no extension.

**Comment by yingzhu146** [comment]
Yes - this is my graph's assets folder. How do I find the file given a workbook?

Also - really appreciate the fast implementation - BUT - I don't think this feature request should be closed - this was about syncing from/to a standard tabular file format that is editable by another spreadsheet software, not about persisting luckysheet metadata in the assets folder (which is good! but not the feature request).

**Comment by sethyuan** [comment]
![image](https://user-images.githubusercontent.com/3410293/197370861-b9495252-828b-4efd-ad24-110236f2ad80.png)

Above is where the files are in your graph, just find them by the workbook name you used in Logseq.

![image](https://user-images.githubusercontent.com/3410293/197370915-83334f9a-1090-4e54-ab81-16df50c8edbc.png)

![image](https://user-images.githubusercontent.com/3410293/197370967-3c7b6cd4-24b9-455d-8785-a590040f94da.png)

Regarding the file format, think of the file stored as an Excel file (.xlsx), there is no such thing as the separation of data and the so called "metadata". And I like I said before, CSV can not be used as the default file format, it has no ability to represent a Luckysheet sheet.

As of the interoperability with the other softwares, you can use the provided "copy selection as TSV" button to export your data in the TSV format. Later, I'll implement a TSV paste feature for importing as well.

**Comment by yingzhu146** [comment]
Thank you! I didn't think it might be in a folder since all other assets are non-nested afaict

> Regarding the file format, think of the file stored as an Excel file (.xlsx), there is no such thing as the separation of data and the so called "metadata".


Yes exactly - which is why Excel is a very bad thing to emulate and against Logseq philosophy :) (using proprietary & non-standard formats which cause lock in - this is why logseq exclusively uses non-proprietary/portable formats wherever possible - PDF, markdown, orgmode, png, jpg. Which is why e.g. you can easily open a logseq graph in obsidian/craft/your_favorite_markdown_editor)

>  And like I said before, CSV can not be used as the default file format, it has no ability to represent a Luckysheet sheet.

Of course it can - you just need to separate metadata from content - that's exactly how PDF annotations are implemented. the content is stored in the standard PDF format, while annotations are stored in a `hls__*.md`. To provide the annotation features, logseq reads these two files.

Analogously, you could easily implement luckysheet such that there's a `meta_$WORKBOOK.md/json/edn` which contains metadata required to represent a luckysheet sheet, and then a `sheet$INDEX_$WORKBOOK.csv` file which contains the contents for sheet X. 

> As of the interoperability with the other softwares, you can use the provided "copy selection as TSV" button to export your data in the TSV format. Later, I'll implement a TSV paste feature for importing as well.

That doesn't solve my use case (avoiding lock in & enabling re-use of the content across software).

Imagine I have 5'000 luckysheet tables and I want to migrate their data from logseq to a database management tool (most of which will be able to load data from csv's)
With the current method I will need to 

- read & understand your code
- re-engineer the json schema
- write a parser
- parse files into CSV.

Now imagine I want to actually keep using both logseq and this database tool in parallel, which means I need to keep them in sync, so  I would additionally need to
- come up with a synchronization strategy
- write a file watcher to run the parser on every save operation

This is a ton of work & leads to unnecessary content duplication

With the implementation I propose you would have to do:

- literally nothing :) - just load/import the CSV. It's guaranteed to be 1) synced 2) portable

Now - all that said - completely okay for you to just say you don't want to solve this use case - but this was the feature request

**Comment by sethyuan** [comment]
You're welcome to make your own implementations. 😉

**Comment by yingzhu146** [comment]
Fair enough! :) thanks for implementing the local persistence so quickly!
