### ISSUE TITLE
render以后不能像demo gif显示那样有个外框，还是markdown的表格

### ISSUE THREAD

**Issue by Joseph-zheng** [sethyuan/logseq-plugin-luckysheet#12]
![Snipaste_2022-10-22_21-51-18](https://user-images.githubusercontent.com/18510737/197342837-60581b58-30c1-48c8-838f-278ca8e8a879.jpg)

![image](https://user-images.githubusercontent.com/18510737/197342907-cc78f0dd-eb60-4abd-abbe-8118b41fc0b5.png)

![Snipaste_2022-10-22_21-52-33](https://user-images.githubusercontent.com/18510737/197342839-3ebc0e3d-0d77-4877-b297-09a49ffcdbec.jpg)

对了，为什么你的logseq选中内容后有float tools, 这是mac和wind的差异吗还是你的插件？谢谢

**Comment by sethyuan** [comment]
我看你截图markdown表格是生成了的，之所以“看起来不一样”是因为每个人用的主题不一样，这个不在插件的控制内。

你看到的工具条是我写的另一个插件的效果， Text Wrapper，它是一个自定义程度非常高的文字包裹插件，工具条是它的一个可选功能。

**Comment by Joseph-zheng** [comment]
谢谢回复~我还以为是win 和mac区别~  非常感谢~ live long and pros
