### ISSUE TITLE
Make it easier to find and open luckysheet files

### ISSUE THREAD

**Issue by bigFin** [sethyuan/logseq-plugin-luckysheet#13]
Right now, creating another reference to an existing luckysheet file requires copying the exact filename. It would be nice to have an open function in the gui or an autocomplete/dropdown while renaming the luckysheet to help us find previously created luckysheets and in a new reference. Bonus points for a Save As function to make it easier to create versions of a sheet.

**Comment by sethyuan** [comment]
1. Renaming can be done by clicking here: ![image](https://user-images.githubusercontent.com/3410293/217401255-8d6f63f4-b203-4d2e-8a5b-a06062219587.png)
2. I recommend you to use a search and complete plugin like [Smart Search](https://github.com/sethyuan/logseq-plugin-smartsearch) for finding sheets. ![image](https://user-images.githubusercontent.com/3410293/217401934-0282d77a-14d4-477c-a5a8-f2ef04deb40b.png)
3. "Save as" functionality can be implemented, I'll look into it later.

**Comment by sethyuan** [comment]
I think this ticket can be closed now. Smart Search is the recommended plugin for searching for content.
