### ISSUE TITLE
建议导出表格为hiccup

### ISSUE THREAD

**Issue by eshion** [sethyuan/logseq-plugin-luckysheet#17]
如果lucksheet上的表格有合并行，则无法导出为markdown表格。因为logseq支持hiccup语法，建议lucksheet导出为hiccup以支持复杂表格。参考如下：

Office&WPS转Logseq表格
https://getquicker.net/Sharedaction?code=7993fcd0-c6ed-4a69-5cb8-08db541d6de4

https://docs.logseq.com/#/page/hiccup

另外如果可以的话，建议可以从markdown表格或hiccup表格导入到lucksheet，这样就可以处理已有的表格，有导入导出功能简直就无敌了！

**Comment by sethyuan** [comment]
hiccup并不像markdown一样是通用格式，也没啥除了看之外的功能，只有Clojure一类的语言会去用，我不确定花时间去支持它是否值得。复杂的表格直接用Luckysheet就好。
