### ISSUE TITLE
保存的表格信息需要如何直接打开呢

### ISSUE THREAD

**Issue by miaozjs** [sethyuan/logseq-plugin-luckysheet#2]
根据说明，我在'.logseq\storages\logseq-luckysheet'中找到的保存的表格文件，文件被保存为类似‘workbook-9f303b8837ccde59ad8016a901a3e8e1b874643e’形式。

1. 尝试过增加文件后缀xlsx，打开失败。
2. luckysheet项目提供的在线工具仅支持xlsx文件。

请问有没有方法可以读取插件自动保存的表格文件？感谢您的插件，给笔记带来了很棒的体验！！！

**Comment by sethyuan** [comment]
Luckysheet保存的数据不是xlsx，它目前还没有完成excel的导出实现（[excel导入导出怎么做？](https://mengshukeji.github.io/LuckysheetDocs/zh/guide/FAQ.html#excel%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E6%80%8E%E4%B9%88%E5%81%9A)）。

Luckysheet数据以JSON格式保存，我在它本身的数据外面包了一层。JSON是一种文本文件，你用任何文本编辑器都可以打开。它的格式描述见它的文档：https://mengshukeji.github.io/LuckysheetDocs/zh/guide/sheet.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%85%8D%E7%BD%AE

如果你是想把它的表格数据拿到其它电子表格软件中去用的话可以考虑用拷贝粘贴操作，或者通过我实现的拷贝TSV的功能拷贝TSV的格式，这种比较通用，但是不带样式。

**Comment by miaozjs** [comment]
> 
文本编辑器打开看了一下，大概明白了，取data就是luckysheet本身的json数据。我本来的想法是能直接打开查看插件保存的表格，那现在就是需要能通过读取data字段里面保存的luckysheet本身的json数来展示表格。找了一下luckysheet社区现在还没有读json展示表格的类似小工具，只有xslx格式的读写工具。

谢谢答复。
