### ISSUE TITLE
安装插件后，命令菜单里没有 luckysheet，为什么？

### ISSUE THREAD

**Issue by caidong85** [sethyuan/logseq-plugin-luckysheet#4]
从logseq 0.6.0版本开始，我在电脑上装了luckysheet，尝试很多版本（无论是logseq还是 lucksheet 官网每发布一个新版本，我都会尝试安装一次，希望能用上luckysheet），logseq命令菜单就是没有lucksheet。我的系统是window10，logseq0.6.7，luckysheet0.6.1。
![图片](https://user-images.githubusercontent.com/102125576/167065501-99560c88-a8e7-41ea-89e9-05da3de78704.png)
![图片](https://user-images.githubusercontent.com/102125576/167065381-c00a4b96-70f5-4ca5-97c0-7703106443e0.png)
![图片](https://user-images.githubusercontent.com/102125576/167065357-7b3dfc8f-eff2-47c5-b7cc-409a4613f700.png)

**Comment by sethyuan** [comment]
你不是用插件市场安装的吧？手动安装可以在 Github 的releases中下载压缩包，解压后在Logseq中加载。
https://github.com/sethyuan/logseq-plugin-luckysheet/releases

**Comment by caidong85** [comment]
我的电脑不能翻墙，所以插件市场不能用，所有插件都是通过 ……/releases 官网地址下载的，解压后放在logseq的plugins目录下，运行logseq，插件就自动加载了，目前所有主题、插件都是这种方法安装的，唯独luckysheet加载后，logseq命令没有luckysheet命令。

**Comment by caidong85** [comment]
要想装上luckysheet，是不是还要装上其他基础软件，如谷歌浏览器，node.js？低版本的office？对了，目前我的系统自带的powershell 1.0 用不了，与这个有关系吗

**Comment by sethyuan** [comment]
不需要的，我估计是你安装插件的方法有问题。插件安装步骤一般是：

1. 到Releases下载zip包
2. 解压到某个文件夹中
3. 在Logseq的插件界面选择“手动载入插件”
4. 选择解压出来的文件夹

![image](https://user-images.githubusercontent.com/3410293/167232218-81805ff6-3911-4f13-99a7-2d0e4f7ad334.png)

**Comment by caidong85** [comment]
前天：其实你说的这种传统安装方法，我之前（一个月前）一直都是这样给logseq安装插件，之前装过luckysheet-v0.4.2，没用！所以前天你告诉我这种安装方法，我无语，我猜测应该是我的系统问题。

今天刚才：我照你的安装方法（传统方法）试了一遍luckysheet-v0.6.1，我去，竟然装上了！感谢你呀，sethyuan。

补充：一个月前，因为在B站上看到”我麋鹿啦、“（好像是他的）教程：传统方法安装插件，装上后，插件市场里会显示”未打包“字样，要想去掉未打包字样，就要把插件解压到软件自带目录下（解压后放在logseq的plugins目录下（C:\Users\NC\.logseq\plugins），然后运行logseq，插件就自动加载了），所以自那之后，我就更改了插件、主题安装方法。这种方法一直很实用，直到遇到luckysheet。后来下午我又折腾了下。其中试了：如果把插件解压到“C:\Users\NC\.logseq\”，运行logseq，然后插件市场手动载入，luckysheet插件可以用（C:\Users\NC\.logseq\settings 目录下会生成logseq-plugin-luckysheet_layouts.json、logseq-plugin-luckysheet.json），也不会显示未打包字样，但是关闭logseq后，重新打开logseq，luckysheet插件不见了，又得插件市场手动载入。所以放弃。最后，只能单独针对luckysheet 采用传统安装方法，然后C:\Users\NC\.logseq\settings 目录下会生成_sethyuan-logseq-luckysheet_layouts.json、_sethyuan-logseq-luckysheet.json。
