### ISSUE TITLE
The sheet cannot be displayed

### ISSUE THREAD

**Issue by baresibest** [sethyuan/logseq-plugin-luckysheet#5]
Using logseq in LAN，and the sheet cannot be displayed
I have installed .net 4.7

**Comment by sethyuan** [comment]
Luckysheet needs to fetch resource files from the internet, the resource files are then cached from there. You need to be sure you are connected to the internet at least the first time you use Luckysheet.

**Comment by baresibest** [comment]
oh......
Can I know what dependencies I need?
The LAN environment cannot be changed

**Comment by sethyuan** [comment]
From what I observed, it tries to load below resources:

![image](https://user-images.githubusercontent.com/3410293/168538327-3d5a13e6-6772-4cc5-b297-be8f9bfcdd0b.png)

![image](https://user-images.githubusercontent.com/3410293/168538456-552a9f9e-4b2c-4815-a071-7475913106ed.png)

![image](https://user-images.githubusercontent.com/3410293/168538521-03e350c5-5531-4878-9469-432a49de33f6.png)

**Comment by baresibest** [comment]
I have upgraded to version 0.7, showing “读取数据错误”，and still Using logseq in LAN

**Comment by baresibest** [comment]
应该是，应该是有些依赖吧。

**Comment by red-co** [comment]
> 我觉得你的问题仍然是没有办法通过网络获取Luckysheet运行所需的全部资源文件。这个问题不好解决，因为我看Luckysheet它就是这样加载的。

能把所需要的资源直接打包到插件文件夹里面吗？

**Comment by sethyuan** [comment]
@red-co 主要是Luckysheet自己的文件加载我控制不了，我发现它就是回去网上下载资源。目前没有找到好的方法能绕开。
