### ISSUE TITLE
`数据读取错误！` - Data loading error caused by wrong substring index

### ISSUE THREAD

**Issue by darioceccoli** [sethyuan/logseq-plugin-luckysheet#7]
Hi, 

Thank you very much for the plugin!

I use the desktop version of Logseq 0.75 on macOS.

After a reindex I get the following error: `数据读取错误！`

When I printed the error that comes out of the exception (`document.getElementById("sheet").innerHTML = '<p class="error">数据读取错误！' + err + '</p>' ;`) I go the following:

```
SyntaxError: Unexpected token ` in JSON at position 69265
```

The issue is in this line:
```
JSON.parse(firstChild.content.substring(7, firstChild.content.length - 3)),
```

I'm not sure whether it's a CR/LF/encoding issue, but for me the correct index is not `-3`, but `-4`.

I locally replaced the line with the issue with the following to patch the issue:
```
JSON.parse(firstChild.content.substring(7, firstChild.content.lastIndexOf(']') + 1)),
```

**Comment by sethyuan** [comment]
Thanks for reporting this! I published a new version using your proposed logic, also fixed the error displaying.
