### ISSUE TITLE
手动添加数据的话只能修改前30条数据。

### ISSUE THREAD

**Issue by rebron1900** [sethyuan/logseq-plugin-luckysheet#9]
如果是复制好数据粘贴进来可以显示30行以后的，但是如果如果一条条录入，到30条就没法再录入数据了。

**Comment by rebron1900** [comment]
另外部分如增加行、删除行的功能无法使用，点击也不会有什么反应。

**Comment by rebron1900** [comment]
而且数据30行后感觉性能下降了

**Comment by sethyuan** [comment]
可以通过在空白处右击菜单里添加行或列，或者右击行或列头，或者右击单元格在菜单里选。

我试了一下增加行、删除行这类的操作，工作是正常的，没能重现问题。

30行就性能下降的问题我这里也没能重现出来。

**Comment by rebron1900** [comment]
> 可以通过在空白处右击菜单里添加行或列，或者右击行或列头，或者右击单元格在菜单里选。
> 
> 我试了一下增加行、删除行这类的操作，工作是正常的，没能重现问题。
> 
> 30行就性能下降的问题我这里也没能重现出来。
> 
> 你表格的数据方便发一份吗？我有空可以用你的数据测试一下。另外你尝试卸载插件并重启一下Logseq试一试，看看会不会是有什么Luckysheet需要的资源文件没有正确下载到。

那我应该是遇到bug了。我现在无法通过右键新增行和列，而且数据多了以后进行修改会有很长时间的等待，我等会把我的 json数据贴出来

**Comment by rebron1900** [comment]
[date.txt](https://github.com/sethyuan/logseq-plugin-luckysheet/files/9390523/date.txt)
数据文件

**Comment by rebron1900** [comment]
我创建issue之前试过卸载插件重启后重新安装，不过还是同样的问题。
操作过程我录了一个视频

https://user-images.githubusercontent.com/7929884/185824216-7b41387c-63dc-4852-b168-d1bc3bc7ab5b.mp4

**Comment by sethyuan** [comment]
我找到问题了。

1. 添加行列的问题是Luckysheet的bug，看起来和你用的公式些有关。建议你反馈到Luckysheet那边看看。
2. 性能问题经过我的排查发现应该是Logseq在新版本中更新块内容变慢导致的，变慢的速度与块内容的大小成正比。目前插件会经常性地保存，内容会保存到第一个子块中，在通过插件SDK向块写入内容时发现有很大的性能问题，写入的内容越大越慢。这个目前我这边也没有特别好的办法解决，只能等Logseq插件SDK实现了对assets的写入开放才能够彻底解决。

**Comment by rebron1900** [comment]
> 我找到问题了。
> 
> 1. 添加行列的问题是Luckysheet的bug，看起来和你用的公式些有关。建议你反馈到Luckysheet那边看看。
> 2. 性能问题经过我的排查发现应该是Logseq在新版本中更新块内容变慢导致的，变慢的速度与块内容的大小成正比。目前插件会经常性地保存，内容会保存到第一个子块中，在通过插件SDK向块写入内容时发现有很大的性能问题，写入的内容越大越慢。这个目前我这边也没有特别好的办法解决，只能等Logseq插件SDK实现了对assets的写入开放才能够彻底解决。

我英文不太好，怕翻译器翻译出来的内容不太贴合原意，能帮我反馈一下吗？
另外全屏的问题好处理么？

**Comment by rebron1900** [comment]
好的。

**Comment by sethyuan** [comment]
我做了个调整，改成在插件加载时去执行写入了，相当于做了个取舍，写入不慢但是启动会慢了。整体感觉要比写入卡顿要好。
